### ISSUE TITLE
Airbrake Integration

### ISSUE THREAD

**Issue by gaurish** [DataDuckETL/DataDuck#5]
If We have this ETL tasks running in production. It be nice to get notified of errors. 

I am willing to work on this feature. But wondering should we start?

**Comment by pickhardt** [comment]
It's easier for me to just add it. I added it this morning for you.

You'll have to upgrade to the latest version: 1.1.0

To use the Airbrake integration, add your project id and project key to your .env file:

AIRBRAKE_PROJECT_ID=123456
AIRBRAKE_PROJECT_KEY=abcdefghijklmnopqrstuvwxyz
